[project]
name = "genai-empowered-personal-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llama-index-readers-google>=0.6.2.post1",
    "strands-agents>=1.1.0",
]
