name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: UV pin Python version
        run: |
          uv python pin ${{ matrix.python-version }}
      - name: uv sync dependencies
        run: |
          uv venv
          uv sync
      - name: Run pylint
        run: |
          uv run pylint $(git ls-files '*.py')
